#!/bin/bash
v=$(cat version)
nv=$((v + 1))
echo "Pushing with name "$1" and version "$nv;
rm version
echo "$nv" > version
git pull origin master
rm -r assets/
unzip -o GRpack.zip
rm readme.txt
echo 'GRPack Ressources. Use with the GR Project only' > readme.txt
git add --all
git commit -m $1
git push origin master
