#!/bin/bash
echo "Pushing with name "$1;
git pull origin master
rm -r assets/
unzip -o GRpack.zip
rm readme.txt
echo 'GRPack Ressources. Use with the GR Project only' > readme.txt
git add --all
git commit -m $1
git push origin master
